sudo: required
language: cpp
install:
- wget https://sourceforge.net/projects/liblo/files/liblo/0.29/liblo-0.29.tar.gz
- gunzip liblo-0.29.tar.gz
- tar -xvf liblo-0.29.tar
- cd liblo-0.29
- ./configure
- sudo make install
- cd ..
script:
- mkdir obj
- mkdir bin
- make
